# Docker Secrets Configuration Example
# For production deployments using Docker Swarm or Kubernetes secrets

# This file demonstrates how to configure secrets for the Nomad application
# Copy this file and modify for your deployment environment

version: '3.8'

# Docker Swarm Secrets Example
secrets:
  notion_token:
    external: true
    # Create with: echo "secret_your_token" | docker secret create notion_token -
    
  notion_board_db:
    external: true
    # Create with: echo "your_database_id" | docker secret create notion_board_db -
    
  openai_api_key:
    external: true
    # Create with: echo "sk-your_key" | docker secret create openai_api_key -
    
  anthropic_api_key:
    external: true
    # Create with: echo "sk-ant-your_key" | docker secret create anthropic_api_key -
    
  openrouter_api_key:
    external: true
    # Create with: echo "sk-or-your_key" | docker secret create openrouter_api_key -
    
  slack_bot_token:
    external: true
    # Create with: echo "xoxb-your_token" | docker secret create slack_bot_token -
    
  slack_app_token:
    external: true
    # Create with: echo "xapp-your_token" | docker secret create slack_app_token -

services:
  nomad:
    image: nomad:latest
    secrets:
      - notion_token
      - notion_board_db
      - openai_api_key
      - anthropic_api_key
      - openrouter_api_key
      - slack_bot_token
      - slack_app_token
    environment:
      # Reference secrets as files (Docker Swarm style)
      - NOTION_TOKEN_FILE=/run/secrets/notion_token
      - NOTION_BOARD_DB_FILE=/run/secrets/notion_board_db
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
      - ANTHROPIC_API_KEY_FILE=/run/secrets/anthropic_api_key
      - OPENROUTER_API_KEY_FILE=/run/secrets/openrouter_api_key
      - SLACK_BOT_TOKEN_FILE=/run/secrets/slack_bot_token
      - SLACK_APP_TOKEN_FILE=/run/secrets/slack_app_token
      
      # Non-sensitive environment variables
      - NOMAD_HOME=/app/.nomad
      - NOMAD_TASKS_DIR=/app/tasks
      - NOMAD_LOG_LEVEL=INFO
      - NOMAD_MAX_CONCURRENT_TASKS=3
      - SLACK_DEFAULT_CHANNEL=#general
      - SLACK_ERROR_CHANNEL=#errors
      - SLACK_NOTIFICATIONS_ENABLED=true
    volumes:
      - nomad_logs:/app/logs
      - nomad_tasks:/app/tasks
      - nomad_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  nomad_logs:
  nomad_tasks:
  nomad_data:

---
# Kubernetes Secrets Example
# Save as kubernetes-secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: nomad-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  # Create with: echo -n "your_value" | base64
  notion-token: c2VjcmV0X3lvdXJfbm90aW9uX3Rva2VuX2hlcmU=
  notion-board-db: eW91cl9ub3Rpb25fZGF0YWJhc2VfaWRfaGVyZQ==
  openai-api-key: c2steW91cl9vcGVuYWlfa2V5X2hlcmU=
  anthropic-api-key: c2stYW50LXlvdXJfYW50aHJvcGljX2tleV9oZXJl
  openrouter-api-key: c2stb3IteW91cl9vcGVucm91dGVyX2tleV9oZXJl
  slack-bot-token: eG94Yi15b3VyX3NsYWNrX2JvdF90b2tlbl9oZXJl
  slack-app-token: eGFwcC15b3VyX3NsYWNrX2FwcF90b2tlbl9oZXJl

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomad
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nomad
  template:
    metadata:
      labels:
        app: nomad
    spec:
      containers:
      - name: nomad
        image: nomad:latest
        env:
        # Secrets from Kubernetes secret
        - name: NOTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: nomad-secrets
              key: notion-token
        - name: NOTION_BOARD_DB
          valueFrom:
            secretKeyRef:
              name: nomad-secrets
              key: notion-board-db
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: nomad-secrets
              key: openai-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nomad-secrets
              key: anthropic-api-key
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: nomad-secrets
              key: openrouter-api-key
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: nomad-secrets
              key: slack-bot-token
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: nomad-secrets
              key: slack-app-token
              
        # Non-sensitive environment variables
        - name: NOMAD_HOME
          value: "/app/.nomad"
        - name: NOMAD_TASKS_DIR
          value: "/app/tasks"
        - name: NOMAD_LOG_LEVEL
          value: "INFO"
        - name: NOMAD_MAX_CONCURRENT_TASKS
          value: "3"
        - name: SLACK_DEFAULT_CHANNEL
          value: "#general"
        - name: SLACK_ERROR_CHANNEL
          value: "#errors"
        - name: SLACK_NOTIFICATIONS_ENABLED
          value: "true"
          
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: tasks
          mountPath: /app/tasks
        - name: data
          mountPath: /app/data
          
        livenessProbe:
          exec:
            command: ["/app/healthcheck.sh"]
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          
        readinessProbe:
          exec:
            command: ["/app/healthcheck.sh"]
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
            
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: nomad-logs-pvc
      - name: tasks
        persistentVolumeClaim:
          claimName: nomad-tasks-pvc
      - name: data
        persistentVolumeClaim:
          claimName: nomad-data-pvc